In [1]:
#working with seismic-bumps datasets and iscx dataset - (attributes = 28, instances = 2990062)

In [2]:
from scipy.io import arff
import pandas as pd


data = arff.loadarff('../ANN/seismic-bumps.arff')
df = pd.DataFrame(data[0])
df.head(10)

data2 = pd.read_csv('../ANN/seismic-bumps.data')
df2 = pd.DataFrame(data2)
df2.head(10)


a a.1  N   15180   48  -72  -72.1 a.2  0  0.1  0.2  0.3  0.4  0.5  0.6  \
0  a   a  N   14720   33  -70    -79   a  1    0    1    0    0    0    0   
1  a   a  N    8050   30  -81    -78   a  0    0    0    0    0    0    0   
2  a   a  N   28820  171  -23     40   a  1    0    1    0    0    0    0   
3  a   a  N   12640   57  -63    -52   a  0    0    0    0    0    0    0   
4  a   a  W   63760  195  -73    -65   a  0    0    0    0    0    0    0   
5  a   a  W  207930  614   -6     18   a  2    2    0    0    0    0    0   
6  a   a  N   48990  194  -27     -3   a  1    0    1    0    0    0    0   
7  a   a  N  100190  303   54     52   a  0    0    0    0    0    0    0   
8  a   a  W  247620  675    4     25   a  1    1    0    0    0    0    0   
9  a   a  N   41950  135  -39    -36   a  1    0    1    0    0    0    0   

   0.7   0.8   0.9  0.10  
0    0  2000  2000     0  
1    0     0     0     0  
2    0  3000  3000     0  
3    0     0     0     0  
4    0     0     0     0  
5    0  1000   700     0  
6    0  4000  4000     0  
7    0     0     0     0  
8    0   500   500     0  
9    0  5000  5000     0

In [3]:
import math
import random
import numpy as np
import pandas as pd
# import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

from sklearn.preprocessing import MultiLabelBinarizer

from scipy.special import expit

from threading import Thread
import time

class InputData():
    # input and output
        # ================== Input dataset and corresponding output ========================= #
        def __init__(self,fileName = "../ANN/seismic-bumps.arff"):
            self.fileName = fileName
            #data = arff.loadarff(fileName)
            #data = pd.DataFrame(data[0])
            data2 = pd.read_csv('../ANN/seismic-bumps.data', header=None)
            df2 = pd.DataFrame(data2)
            data = df2
            
            output_values_expected = []
            input_values = []

            # ~~~~ encoding ~~~~#

            # labelencoder = LabelEncoder()
            # data[data.columns[-1]] = labelencoder.fit_transform(data[data.columns[-1]])

            # one hot encoding - for multi-column
            # enc = OneHotEncoder(handle_unknown='ignore')
            # combinedData = np.vstack((data[data.columns[-2]], data[data.columns[-1]])).T
            # print(combinedData)
            # y = enc.fit_transform(combinedData).toarray()
            # y = OneHotEncoder().fit_transform(combinedData).toarray()


            y = LabelBinarizer().fit_transform(data.iloc[:,-1])
            # print(y)

            # ~~~~ encoding ends~~~~#

            for j in range(len(data)):
                output_values_expected.append(y[j])

            # print(output_values_expected)
            labelencoder = LabelEncoder()

            for j in range(len(data.columns)):
                b = []
                if(isinstance(data.iloc[0,j], (int, np.integer))):
                    b.append(data.iloc[:,j])
                    input_values.extend(b)
                else:
                    b.append(labelencoder.fit_transform(data.iloc[:,j]))
                    input_values.extend(b)

            self.X = input_values[:]
            self.Y = output_values_expected[:]
        def main(self):
            return (self.X, self.Y)

In [4]:
i = InputData()
x,y = i.main()
x = [[x[j][i] for j in range(len(x))] for i in range(len(x[0]))]

In [5]:
x

[[0, 0, 0, 15180, 48, -72, -72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 14720, 33, -70, -79, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2000, 2000, 0],
 [0, 0, 0, 8050, 30, -81, -78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 28820, 171, -23, 40, 0, 1, 0, 1, 0, 0, 0, 0, 0, 3000, 3000, 0],
 [0, 0, 0, 12640, 57, -63, -52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 63760, 195, -73, -65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 207930, 614, -6, 18, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1000, 700, 0],
 [0, 0, 0, 48990, 194, -27, -3, 0, 1, 0, 1, 0, 0, 0, 0, 0, 4000, 4000, 0],
 [0, 0, 0, 100190, 303, 54, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 247620, 675, 4, 25, 0, 1, 1, 0, 0, 0, 0, 0, 0, 500, 500, 0],
 [0, 0, 0, 41950, 135, -39, -36, 0, 1, 0, 1, 0, 0, 0, 0, 0, 5000, 5000, 0],
 [0, 0, 0, 53250, 140, -19, -31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 166180, 448, -30, -19, 0, 1, 1, 0, 0, 0, 0, 0, 0, 400, 400, 0],
 [0, 0, 0, 64540, 215, 0, 9, 0, 1, 0, 1, 0, 0, 0, 0, 0, 6000, 6

In [6]:
y

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [7]:
import math
import random
import numpy as np
import pandas as pd
# import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

from sklearn.preprocessing import MultiLabelBinarizer

from scipy.special import expit

from threading import Thread
import time

from scipy.io import arff
import pandas as pd


#data = arff.loadarff('../ANN/seismic-bumps.arff')
#df = pd.DataFrame(data[0])
#df.head(10)

data2 = pd.read_csv('../../../downloads/datasett22/dataset_attack.csv')
df2 = pd.DataFrame(data2)
df2.head(10)
data = df2


y = LabelBinarizer().fit_transform(data.iloc[:,-1])
# print(y)

# ~~~~ encoding ends~~~~#
output_values_expected = []
input_values = []

for j in range(len(data)):
    output_values_expected.append(y[j])

# print(output_values_expected)
labelencoder = LabelEncoder()

for j in range(len(data.columns)-1):
    b = []
    if(isinstance(data.iloc[0,j], (int, np.integer))):
        b.append(data.iloc[:,j])
        input_values.extend(b)
    else:
        b.append(labelencoder.fit_transform(data.iloc[:,j]))
        input_values.extend(b)
input_values = np.array(input_values)
output_values = np.array(output_values_expected)

In [8]:
x = np.asarray(input_values).astype(np.float32).T
print("X = ",x)

X =  [[2.120e+02 1.930e+02 2.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.120e+02 1.930e+02 2.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.120e+02 1.930e+02 2.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.434e+03 9.000e+00 2.000e+01 ... 0.000e+00 5.840e+03 4.005e+03]
 [6.000e+01 9.000e+00 2.000e+01 ... 0.000e+00 1.656e+04 1.352e+03]
 [1.434e+03 9.000e+00 2.000e+01 ... 0.000e+00 5.840e+03 2.139e+03]]


In [9]:
print("attributes = ",len(x[0]))
print("instances = ",len(x))

attributes =  28
instances =  2990062


In [10]:
print("Y = ", output_values)

Y =  [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
