In [1]:
#working with seismic-bumps datasets and iscx dataset - (attributes = 28, instances = 2990062)

In [2]:
from scipy.io import arff
import pandas as pd


data = arff.loadarff('../ANN/seismic-bumps.arff')
df = pd.DataFrame(data[0])
df.head(10)

data2 = pd.read_csv('../ANN/seismic-bumps.data')
df2 = pd.DataFrame(data2)
df2.head(10)


a a.1  N   15180   48  -72  -72.1 a.2  0  0.1  0.2  0.3  0.4  0.5  0.6  \
0  a   a  N   14720   33  -70    -79   a  1    0    1    0    0    0    0   
1  a   a  N    8050   30  -81    -78   a  0    0    0    0    0    0    0   
2  a   a  N   28820  171  -23     40   a  1    0    1    0    0    0    0   
3  a   a  N   12640   57  -63    -52   a  0    0    0    0    0    0    0   
4  a   a  W   63760  195  -73    -65   a  0    0    0    0    0    0    0   
5  a   a  W  207930  614   -6     18   a  2    2    0    0    0    0    0   
6  a   a  N   48990  194  -27     -3   a  1    0    1    0    0    0    0   
7  a   a  N  100190  303   54     52   a  0    0    0    0    0    0    0   
8  a   a  W  247620  675    4     25   a  1    1    0    0    0    0    0   
9  a   a  N   41950  135  -39    -36   a  1    0    1    0    0    0    0   

   0.7   0.8   0.9  0.10  
0    0  2000  2000     0  
1    0     0     0     0  
2    0  3000  3000     0  
3    0     0     0     0  
4    0     0     0     0  
5    0  1000   700     0  
6    0  4000  4000     0  
7    0     0     0     0  
8    0   500   500     0  
9    0  5000  5000     0

In [1]:
import math
import random
import numpy as np
import pandas as pd
# import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

from sklearn.preprocessing import MultiLabelBinarizer

from scipy.special import expit

from threading import Thread
import time

class InputData():
    # input and output
        # ================== Input dataset and corresponding output ========================= #
        def __init__(self,fileName = "../ANN/seismic-bumps.arff"):
            self.fileName = fileName
            #data = arff.loadarff(fileName)
            #data = pd.DataFrame(data[0])
            data2 = pd.read_csv('../ANN/seismic-bumps.data', header=None)
            df2 = pd.DataFrame(data2)
            data = df2
            
            output_values_expected = []
            input_values = []

            # ~~~~ encoding ~~~~#

            # labelencoder = LabelEncoder()
            # data[data.columns[-1]] = labelencoder.fit_transform(data[data.columns[-1]])

            # one hot encoding - for multi-column
            # enc = OneHotEncoder(handle_unknown='ignore')
            # combinedData = np.vstack((data[data.columns[-2]], data[data.columns[-1]])).T
            # print(combinedData)
            # y = enc.fit_transform(combinedData).toarray()
            # y = OneHotEncoder().fit_transform(combinedData).toarray()


            y = LabelBinarizer().fit_transform(data.iloc[:,-1])
            # print(y)

            # ~~~~ encoding ends~~~~#

            for j in range(len(data)):
                output_values_expected.append(y[j])

            # print(output_values_expected)
            labelencoder = LabelEncoder()

            for j in range(len(data.columns)):
                b = []
                if(isinstance(data.iloc[0,j], (int, np.integer))):
                    b.append(data.iloc[:,j])
                    input_values.extend(b)
                else:
                    b.append(labelencoder.fit_transform(data.iloc[:,j]))
                    input_values.extend(b)

            self.X = input_values[:]
            self.Y = output_values_expected[:]
        def main(self):
            return (self.X, self.Y)

In [2]:
from sklearn.model_selection import train_test_split
i = InputData()
x,y = i.main()
x = [[x[j][i] for j in range(len(x))] for i in range(len(x[0]))]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [9]:
x

[[0, 0, 0, 15180, 48, -72, -72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 14720, 33, -70, -79, 0, 1, 0, 1, 0, 0, 0, 0, 0, 2000, 2000, 0],
 [0, 0, 0, 8050, 30, -81, -78, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 28820, 171, -23, 40, 0, 1, 0, 1, 0, 0, 0, 0, 0, 3000, 3000, 0],
 [0, 0, 0, 12640, 57, -63, -52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 63760, 195, -73, -65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 207930, 614, -6, 18, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1000, 700, 0],
 [0, 0, 0, 48990, 194, -27, -3, 0, 1, 0, 1, 0, 0, 0, 0, 0, 4000, 4000, 0],
 [0, 0, 0, 100190, 303, 54, 52, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 247620, 675, 4, 25, 0, 1, 1, 0, 0, 0, 0, 0, 0, 500, 500, 0],
 [0, 0, 0, 41950, 135, -39, -36, 0, 1, 0, 1, 0, 0, 0, 0, 0, 5000, 5000, 0],
 [0, 0, 0, 53250, 140, -19, -31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 166180, 448, -30, -19, 0, 1, 1, 0, 0, 0, 0, 0, 0, 400, 400, 0],
 [0, 0, 0, 64540, 215, 0, 9, 0, 1, 0, 1, 0, 0, 0, 0, 0, 6000, 6

In [4]:
y

[array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([1]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),
 array([0]),

In [6]:
len(X_train)

2067

In [10]:
len(X_test)

517

In [11]:
len(y_train)

2067

In [12]:
len(y_test)

517

In [14]:
import math
import random
import numpy as np
import pandas as pd
# import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelBinarizer

from sklearn.preprocessing import MultiLabelBinarizer

from scipy.special import expit

from threading import Thread
import time

from scipy.io import arff
import pandas as pd


#data = arff.loadarff('../ANN/seismic-bumps.arff')
#df = pd.DataFrame(data[0])
#df.head(10)

data2 = pd.read_csv('../../../downloads/datasett22/dataset_attack.csv')
df2 = pd.DataFrame(data2)
df2.head(10)
data = df2


y = LabelBinarizer().fit_transform(data.iloc[:,-1])
# print(y)

# ~~~~ encoding ends~~~~#
output_values_expected = []
input_values = []

for j in range(len(data)):
    output_values_expected.append(y[j])

# print(output_values_expected)
labelencoder = LabelEncoder()

for j in range(len(data.columns)-1):
    b = []
    if(isinstance(data.iloc[0,j], (int, np.integer))):
        b.append(data.iloc[:,j])
        input_values.extend(b)
    else:
        b.append(labelencoder.fit_transform(data.iloc[:,j]))
        input_values.extend(b)
input_values = np.array(input_values)
output_values = np.array(output_values_expected)

In [15]:
x = np.asarray(input_values).astype(np.float32).T
print("X = ",x)

X =  [[2.120e+02 1.930e+02 2.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.120e+02 1.930e+02 2.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 [2.120e+02 1.930e+02 2.000e+01 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [1.434e+03 9.000e+00 2.000e+01 ... 0.000e+00 5.840e+03 4.005e+03]
 [6.000e+01 9.000e+00 2.000e+01 ... 0.000e+00 1.656e+04 1.352e+03]
 [1.434e+03 9.000e+00 2.000e+01 ... 0.000e+00 5.840e+03 2.139e+03]]


In [16]:
print("attributes = ",len(x[0]))
print("instances = ",len(x))

attributes =  28
instances =  2990062


In [24]:
print("Y = ", output_values)
y = output_values

Y =  [[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [22]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(x, y, test_size=0.2)

In [34]:
class InputData():
    # input and output
    # ================== Input dataset and corresponding output ========================= #
    def __init__(self, fileName="../ANN/winequality-white"):
        self.fileName = fileName
        self.fileName += ".csv"
        data = pd.read_csv(self.fileName, sep=';', )
        data = data.infer_objects()

        output_values_expected = []
        input_values = []
        print(data)

        # ~~~~ encoding ~~~~#

        # labelencoder = LabelEncoder()
        # data[data.columns[-1]] = labelencoder.fit_transform(data[data.columns[-1]])

        # one hot encoding - for multi-column
        # enc = OneHotEncoder(handle_unknown='ignore')
        # combinedData = np.vstack((data[data.columns[-2]], data[data.columns[-1]])).T
        # print(combinedData)
        # y = enc.fit_transform(combinedData).toarray()
        # y = OneHotEncoder().fit_transform(combinedData).toarray()

        y = LabelBinarizer().fit_transform(data[data.columns[-1]])
        # print(y)

        # ~~~~ encoding ends~~~~#

        for j in range(len(data)):
            output_values_expected.append(y[j])

        # print(output_values_expected)

        for j in range(len(data)):
            b = []
            for i in range(len(data.columns) - 1):
                b.append(data[data.columns[i]][j])
            input_values.append(b)

        self.X = input_values[:]
        self.Y = output_values_expected[:]

    def main(self):
        return (self.X, self.Y)

In [35]:
i = InputData()
x,y = i.main()

      fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.0              0.27         0.36            20.7      0.045   
1               6.3              0.30         0.34             1.6      0.049   
2               8.1              0.28         0.40             6.9      0.050   
3               7.2              0.23         0.32             8.5      0.058   
4               7.2              0.23         0.32             8.5      0.058   
...             ...               ...          ...             ...        ...   
4893            6.2              0.21         0.29             1.6      0.039   
4894            6.6              0.32         0.36             8.0      0.047   
4895            6.5              0.24         0.19             1.2      0.041   
4896            5.5              0.29         0.30             1.1      0.022   
4897            6.0              0.21         0.38             0.8      0.020   

      free sulfur dioxide  

In [36]:
x

[[7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8],
 [6.3, 0.3, 0.34, 1.6, 0.049, 14.0, 132.0, 0.994, 3.3, 0.49, 9.5],
 [8.1, 0.28, 0.4, 6.9, 0.05, 30.0, 97.0, 0.9951, 3.26, 0.44, 10.1],
 [7.2, 0.23, 0.32, 8.5, 0.058, 47.0, 186.0, 0.9956, 3.19, 0.4, 9.9],
 [7.2, 0.23, 0.32, 8.5, 0.058, 47.0, 186.0, 0.9956, 3.19, 0.4, 9.9],
 [8.1, 0.28, 0.4, 6.9, 0.05, 30.0, 97.0, 0.9951, 3.26, 0.44, 10.1],
 [6.2, 0.32, 0.16, 7.0, 0.045, 30.0, 136.0, 0.9949, 3.18, 0.47, 9.6],
 [7.0, 0.27, 0.36, 20.7, 0.045, 45.0, 170.0, 1.001, 3.0, 0.45, 8.8],
 [6.3, 0.3, 0.34, 1.6, 0.049, 14.0, 132.0, 0.994, 3.3, 0.49, 9.5],
 [8.1, 0.22, 0.43, 1.5, 0.044, 28.0, 129.0, 0.9938, 3.22, 0.45, 11.0],
 [8.1, 0.27, 0.41, 1.45, 0.033, 11.0, 63.0, 0.9908, 2.99, 0.56, 12.0],
 [8.6, 0.23, 0.4, 4.2, 0.035, 17.0, 109.0, 0.9947, 3.14, 0.53, 9.7],
 [7.9, 0.18, 0.37, 1.2, 0.04, 16.0, 75.0, 0.992, 3.18, 0.63, 10.8],
 [6.6, 0.16, 0.4, 1.5, 0.044, 48.0, 143.0, 0.9912, 3.54, 0.52, 12.4],
 [8.3, 0.42, 0.62, 19.25, 0.04, 41.